
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import firebase_admin
from customtkinter import CTkFrame, CTk, CTkLabel
from firebase_admin import credentials
from firebase_admin import firestore

cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)

db = firestore.client()

# Fetch data from Firestore where GRDStatus is 'Approved'
clinics_ref = db.collection('Clinics').where('GRDStatus', '==', 'Approved')
docs = clinics_ref.stream()

# Prepare the data
clinic_data = []
for doc in docs:
    clinic_data.append(doc.to_dict())

root = CTk()
root.title("Clinics with Approved GRDStatus")

frame = CTkFrame(master=root, corner_radius=15, width=600, height=400)
frame.pack(pady=20, padx=20, fill="both", expand=True)

# Display each clinic data
for clinic in clinic_data:
    clinic_info = (
        f"Name: {clinic.get('Name', 'N/A')}\n"
        f"Email: {clinic.get('Email', 'N/A')}\n"
        f"PhoneNo: {clinic.get('PhoneNo', 'N/A')}\n"
        f"Address: {clinic.get('Address', 'N/A')}\n"
        f"GRDStatus: {clinic.get('GRDStatus', 'N/A')}"
    )
    label = CTkLabel(
        master=frame,
        text=clinic_info,
        width=550,
        height=100,
        corner_radius=15,
        fg_color="white",
        text_color="black",
        justify='left'
    )
    label.pack(pady=10, padx=10)

root.mainloop()

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\INTI homework\Degree  in Computer Scince BCSCUN\Software Engineering\Assignment\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1080x664")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 664,
    width = 1080,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    540.0,
    332.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    666.0,
    240.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=332.5,
    y=211.0,
    width=667.0,
    height=57.0
)

canvas.create_rectangle(
    81.0,
    0.0,
    1080.0,
    198.0,
    fill="#FFFFFF",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    591.0,
    410.0,
    image=image_image_2
)

canvas.create_text(
    502.0,
    395.0,
    anchor="nw",
    text="Location: Bayan Lepas, Penang\nHours: Open ⋅ Closes 9 pm\nSpeciality: General medical clinic ",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    502.0,
    334.0,
    anchor="nw",
    text="Klinik Singapore Relau",
    fill="#5D5D5D",
    font=("Inter Bold", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=986.0,
    y=211.0,
    width=25.0,
    height=59.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    313.0,
    410.0,
    image=image_image_3
)

canvas.create_rectangle(
    0.0,
    0.0,
    81.0,
    664.0,
    fill="#5271FF",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=305.0,
    width=81.0,
    height=73.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1015.0,
    y=0.0,
    width=65.0,
    height=60.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    591.0,
    99.0,
    image=image_image_4
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=0.0,
    width=81.0,
    height=73.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=0.0,
    y=167.0,
    width=81.0,
    height=73.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=154.0,
    y=211.0,
    width=206.0,
    height=59.0
)

canvas.create_rectangle(
    362.0,
    219.0,
    363.0,
    261.0,
    fill="#5271FF",
    outline="")
window.resizable(False, False)
window.mainloop()
